# Generated by Django 4.0.4 on 2022-05-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoshop', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
